{% set name = "gh repo clone AdMax18/awscli-local-feedstock" %}
{% set version = "0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 861d0b7d09c7210052a19393f1877115ec6e5e08430ab48f12be8414bd90bda5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - awscli
    - localstack-client
    - python >=3.6

test:
  commands:
    - awslocal -h

about:
  home: https://github.com/localstack/awscli-local
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Thin wrapper around the "aws" command line interface for use with LocalStack
  doc_url: https://pypi.org/project/awscli-local/
  dev_url: https://github.com/localstack/awscli-local

extra:
  recipe-maintainers:
    - mwilson8
    - mxr-conda
