{% set name = "awscli-local" %}
{% set version = "0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07e33d9de7868e262a3ea3e01f43e24149874f544b48ae4f15d46e4632413f57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - awscli
    - localstack-client
    - python

test:
  commands:
    - awslocal -h

about:
  home: https://github.com/localstack/awscli-local
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Thin wrapper around the "aws" command line interface for use with LocalStack
  doc_url: https://pypi.org/project/awscli-local/
  dev_url: https://github.com/localstack/awscli-local

extra:
  recipe-maintainers:
    - mwilson8
    - oblute
    - benhuff
