travis:
  secure:
    BINSTAR_TOKEN: ezDaFp/MUFYhc8qOFyTxScSAEGwnrnYRXRt42EkUON9Tag03l74osId5HUooiVAZTbtaX4lQZdAGiUdQQ0HztNwWSQgeDoAk3wQ4H39TNdnEcEwOQE7GMkelZCzBQjgb11v+X+aDmrD9GrubE3JBxwFtTNB1dQfdfYChSywOIKBmkXEVgG6l4JoEdY1YQqIijp+vFVdWBUOzPrYUJqhI/mQQexH6yv/NsBjDHzxXPU1KcMztrq6WLDnWw+DNGNaoC3rr73cja3sLxU/Uf4AGe9R83PRe578cUVJItqKkiKlea58CikgrKCda9FjGGdTJceOlkrbfrse5Tq0VNipQzlZ2W1L1v+m5LPIad6oJpHK/6DIg0v1HiirngSdMb5VqH+YxLl/HQeSZtpr2Ubm0bQ9KzDrn2MSX0zmtxw8dEyTf2l9Hah9gceJcEZ2Q1ONuKeRJmYPlxwXr6x7jfYsWrFt7L8nGe901vccsZcE9yBIUguV3gqpunPHbS2XMqetsdn8xxrqX6GmVy6oDaGscE7nVSbdtSHtSI5qCQ8T+Wt8WhGOHYxXeZcBSdt4LSr8ScdKt8tWD2NeKBF/VnfinpMtYF0OgtxkWrafalMD/sNncH9jhpDTerRx2bZN7wWpMlc8LyWk6ETdDuQtGx5PDr2WDyHG7TTd0NV5+nBCoQEg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
