travis:
  secure:
    BINSTAR_TOKEN: Dg5K+Mcc4Jsr+yF7Q7w5BAuTk0z9DBkLzq6ZYClDLnnCt1CkQs7/Iwj/U/t68OACw8bjVuIPp28JalVsj/LimYcmbgBs2DV4XszAUBrckDNbcC9T3iZ82aEE6kGw8WYUg7inFjFS6yDPjeNtRPnmoteqIgmubnHtW/VdOsnq60o7EiNulcFoAmiMTIQ+aSwuw3jagu9Q0Rs6bosXDual3IGXYdzrIBkyQAHXkfSFpDo6L4SgUR5HHQ6NRMHEi7XM4+5Fa/wNb085E4LFMwnhK/R/vW3x+iZ6rrxeoG75rY6DmS6sRVeD5/44TQMIraoc2Z8a2vsE2WYvT38GeeidQvShmFZ8bra5JWPo47vI6MeFz/TRUgDvHzERns8b1hF2taxpsyF4kKnSUI45zXFXp+rwK+PgjEl4MWr9+lppVWD1Xo1/i+ebL9FC4/te9eunG8ocLzZh+sRUWhXUSCR54DQ3eaYXptmQskaB4jTYUaDqJhPwmyCyJF93RdCYzk0jy84+hqmR4si2O4Yw8UTGCfch7vRIGYekbKIshO5HF2SxopbJKJVyP8yb6CTBxwLGpj2aG9Y0caY4mEw3BL7mnOfRSY1+fc39c6oQOcZVCXzUUEtBnlXiSBS03ydcmuelAsrmCZukrRgF7yHxgM9UZ87FJaPMHqB2SWx8hxF+wAU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
